### PR TITLE
Fixed paths in files generated by cannon-init

### PR DESCRIPTION
**Pull request by kieranajp**
As noted in #1

### CODE REVIEW

**Comment by jackfranklin** [comment]
Awesome, thank you!

**Comment by jackfranklin** [comment]
I need to write a properly customisable CLI at some point...

**Comment by kieranajp** [comment]
@jackfranklin No probs!

While we're talking to-dos, the logical thing for me would be to have this set up so you can write posts in Markdown (using [this](https://www.npmjs.com/package/markdown-react) for example). So yeah, feature request that I may look into implementing when I have time (e.g. not for a few weeks!) if it's okay with you.

**Comment by jackfranklin** [comment]
@kieranajp yeah, my thoughts on this are that Cannon should provide a component or something that lets you write Markdown but it shouldn't make it mandatory. If you'd like to work on that feel free :)

**Pull request merged**
